"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useMemo, useState } from "react";
import { apiRequest } from "@/features/admin/api/admin.api";
import { useAdminResource } from "./admin-kit";

type Version={id:string;version_number:number;status:string;capabilities:Record<string,unknown>;form_schema:unknown[];adapter_instruction:string;compiled_checksum:string|null;modules:{id:string;position:number;module_title:string;module_key:string;module_version:number}[]};
type Target={id:string;key:string;label:string;media_type:string;product_provider_label:string|null;description:string;active:boolean;public:boolean;recommended:boolean;display_order:number;official_docs_url:string|null;published_version:string|null;current_published_version_id:string|null;versions:Version[]};
type Tab="main"|"capabilities"|"instructions"|"tests"|"versions";

export default function AITargetEditorPage(){
  const {id}=useParams<{id:string}>();
  const resource=useAdminResource<Target>(`/admin/prompt-builder/targets/${id}`);
  const [tab,setTab]=useState<Tab>("main");
  const [notice,setNotice]=useState("");
  const [error,setError]=useState("");
  const target=resource.data;
  const draft=useMemo(()=>target?.versions.find(v=>v.status==="draft"||v.status==="testing"),[target]);
  async function saveTarget(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!target)return;const f=new FormData(event.currentTarget);setError("");try{await apiRequest(`/admin/prompt-builder/targets/${target.id}`,{method:"PATCH",body:JSON.stringify({label:f.get("label"),product_provider_label:f.get("provider"),description:f.get("description"),display_order:Number(f.get("order")),official_docs_url:f.get("docs")||null,active:f.get("active")==="on",public:f.get("public")==="on",recommended:f.get("recommended")==="on"})});setNotice("Profil saqlandi");await resource.reload();}catch(e){setError(e instanceof Error?e.message:"Saqlashda xato");}}
  async function createDraft(){if(!target)return;await apiRequest(`/admin/prompt-builder/targets/${target.id}/versions`,{method:"POST",body:JSON.stringify({})});setNotice("Yangi draft yaratildi");await resource.reload();}
  async function saveVersion(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!draft)return;const f=new FormData(event.currentTarget);try{await apiRequest(`/admin/prompt-builder/target-versions/${draft.id}`,{method:"PATCH",body:JSON.stringify({adapter_instruction:f.get("adapter"),capabilities:JSON.parse(String(f.get("capabilities"))),form_schema:JSON.parse(String(f.get("form_schema")))})});setNotice("Draft saqlandi");await resource.reload();}catch(e){setError(e instanceof Error?e.message:"JSON yoki server xatosi");}}
  async function test(){if(!draft)return;const result=await apiRequest<{passed:boolean}>(`/admin/prompt-builder/target-versions/${draft.id}/test`,{method:"POST",body:JSON.stringify({target_version_id:draft.id,provider_key:"auto",idea:"A cinematic product scene for deterministic regression testing",settings:{}})});setNotice(result.passed?"Barcha tekshiruvlardan o‘tdi":"Tekshiruvda muammo topildi");await resource.reload();}
  async function publish(){if(!draft)return;await apiRequest(`/admin/prompt-builder/target-versions/${draft.id}/publish`,{method:"POST",body:JSON.stringify({override_warnings:false,reason:"Regression tests passed"})});setNotice("Versiya publish qilindi");await resource.reload();}
  if(resource.loading)return <p className="ai-studio-message">Profil yuklanmoqda…</p>;
  if(!target)return <p className="ai-studio-message error">{resource.error||"Model topilmadi"}</p>;
  const tabs:[Tab,string][]=[["main","Asosiy"],["capabilities","Imkoniyatlar"],["instructions","Yo‘riqnomalar"],["tests","Testlar"],["versions","Versiyalar"]];
  return <div className="ai-studio target-editor"><Link className="ai-back" href="/admin/ai-assistant">← Prompt modellariga qaytish</Link><header className="ai-target-head"><div><h1>{target.label}</h1><p>{target.description}</p></div><button className="button button-ghost" onClick={()=>void createDraft()}>+ Yangi draft</button><button className="button button-ghost" disabled={!draft} onClick={()=>void test()}>Test qilish</button><button className="button button-primary" disabled={!draft} onClick={()=>void publish()}>Publish</button></header><nav className="ai-studio-tabs">{tabs.map(([k,l])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</nav>{notice&&<p className="ai-studio-message success">{notice}</p>}{error&&<p className="ai-studio-message error">{error}</p>}
  {tab==="main"&&<form className="ai-editor-grid" onSubmit={saveTarget}><section className="ai-studio-card ai-form"><h2>Profil ma’lumotlari</h2><label>Ichki kalit<input value={target.key} disabled/></label><label>Ko‘rinish nomi<input name="label" defaultValue={target.label}/></label><label>Provider / Mahsulot<input name="provider" defaultValue={target.product_provider_label??""}/></label><label>Qisqa tavsif<textarea name="description" defaultValue={target.description}/></label><label>Rasmiy hujjatlar URL<input name="docs" defaultValue={target.official_docs_url??""}/></label><label>Display order<input name="order" type="number" defaultValue={target.display_order}/></label><label className="ai-check"><input name="active" type="checkbox" defaultChecked={target.active}/> Active</label><label className="ai-check"><input name="public" type="checkbox" defaultChecked={target.public}/> Public</label><label className="ai-check"><input name="recommended" type="checkbox" defaultChecked={target.recommended}/> Recommended</label><button className="button button-primary">Profilni saqlash</button></section><aside className="ai-studio-card ai-state"><h2>Holat</h2><p>Published versiya <b>{target.published_version??"—"}</b></p><p>Joriy draft <b>{draft?`v${draft.version_number}`:"—"}</b></p><p>Ulangan modullar <b>{draft?.modules.length??0}</b></p><p>Jami versiyalar <b>{target.versions.length}</b></p></aside></form>}
  {(tab==="capabilities"||tab==="instructions")&&draft&&<form className="ai-studio-card ai-form" onSubmit={saveVersion}><h2>{tab==="capabilities"?"Capability manifest va user form schema":"Model adapteri va yo‘riqnoma kompozitsiyasi"}</h2>{tab==="instructions"&&<div className="ai-module-list">{draft.modules.map(m=><div key={m.id}><b>{m.position}. {m.module_title}</b><span>{m.module_key} · v{m.module_version}</span></div>)}</div>}<label>Model adapteri<textarea name="adapter" rows={10} defaultValue={draft.adapter_instruction}/></label><label>Capabilities JSON<textarea name="capabilities" rows={12} defaultValue={JSON.stringify(draft.capabilities,null,2)}/></label><label>Form schema JSON<textarea name="form_schema" rows={12} defaultValue={JSON.stringify(draft.form_schema,null,2)}/></label><button className="button button-primary">Draftni saqlash</button></form>}
  {tab==="tests"&&<section className="ai-studio-card"><h2>Regression testlari</h2><p>Adapter, capability, form schema va modul kompozitsiyasi publishdan oldin tekshiriladi.</p><button className="button button-primary" disabled={!draft} onClick={()=>void test()}>Barchasini ishga tushirish</button></section>}
  {tab==="versions"&&<section className="ai-studio-card"><h2>{target.label} versiyalari</h2><div className="ai-studio-table versions"><div className="head"><span>Versiya</span><span>Holat</span><span>Modullar</span><span>Checksum</span><span>Amal</span></div>{target.versions.map(v=><div className="row" key={v.id}><b>v{v.version_number}</b><span>{v.status}</span><span>{v.modules.length}</span><span>{v.compiled_checksum?.slice(0,12)??"—"}</span><button disabled={v.status==="published"} onClick={()=>setTab("instructions")}>Ochish</button></div>)}</div></section>}
  </div>;
}
